// Generated by gencpp from file project_ros_python/get_degree.msg
// DO NOT EDIT!


#ifndef PROJECT_ROS_PYTHON_MESSAGE_GET_DEGREE_H
#define PROJECT_ROS_PYTHON_MESSAGE_GET_DEGREE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_ros_python
{
template <class ContainerAllocator>
struct get_degree_
{
  typedef get_degree_<ContainerAllocator> Type;

  get_degree_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , imu_time_stamp(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
    }
  get_degree_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , imu_time_stamp(0.0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _imu_time_stamp_type;
  _imu_time_stamp_type imu_time_stamp;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;





  typedef boost::shared_ptr< ::project_ros_python::get_degree_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_ros_python::get_degree_<ContainerAllocator> const> ConstPtr;

}; // struct get_degree_

typedef ::project_ros_python::get_degree_<std::allocator<void> > get_degree;

typedef boost::shared_ptr< ::project_ros_python::get_degree > get_degreePtr;
typedef boost::shared_ptr< ::project_ros_python::get_degree const> get_degreeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_ros_python::get_degree_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_ros_python::get_degree_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_ros_python

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'project_ros_python': ['/home/jetbot/project_black/src/project_ros_python/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_python::get_degree_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_python::get_degree_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_python::get_degree_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_python::get_degree_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_python::get_degree_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_python::get_degree_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_ros_python::get_degree_<ContainerAllocator> >
{
  static const char* value()
  {
    return "054328748e3098a2957873e08b7881f8";
  }

  static const char* value(const ::project_ros_python::get_degree_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x054328748e3098a2ULL;
  static const uint64_t static_value2 = 0x957873e08b7881f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_ros_python::get_degree_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_ros_python/get_degree";
  }

  static const char* value(const ::project_ros_python::get_degree_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_ros_python::get_degree_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"float32 imu_time_stamp\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
;
  }

  static const char* value(const ::project_ros_python::get_degree_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_ros_python::get_degree_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.imu_time_stamp);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_degree_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_ros_python::get_degree_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_ros_python::get_degree_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "imu_time_stamp: ";
    Printer<float>::stream(s, indent + "  ", v.imu_time_stamp);
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_ROS_PYTHON_MESSAGE_GET_DEGREE_H
