// Generated by gencpp from file project_ros_cpp/clean_point.msg
// DO NOT EDIT!


#ifndef PROJECT_ROS_CPP_MESSAGE_CLEAN_POINT_H
#define PROJECT_ROS_CPP_MESSAGE_CLEAN_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_ros_cpp
{
template <class ContainerAllocator>
struct clean_point_
{
  typedef clean_point_<ContainerAllocator> Type;

  clean_point_()
    : clean_data()
    , max_gird_point(0)  {
    }
  clean_point_(const ContainerAllocator& _alloc)
    : clean_data(_alloc)
    , max_gird_point(0)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _clean_data_type;
  _clean_data_type clean_data;

   typedef int32_t _max_gird_point_type;
  _max_gird_point_type max_gird_point;





  typedef boost::shared_ptr< ::project_ros_cpp::clean_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_ros_cpp::clean_point_<ContainerAllocator> const> ConstPtr;

}; // struct clean_point_

typedef ::project_ros_cpp::clean_point_<std::allocator<void> > clean_point;

typedef boost::shared_ptr< ::project_ros_cpp::clean_point > clean_pointPtr;
typedef boost::shared_ptr< ::project_ros_cpp::clean_point const> clean_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_ros_cpp::clean_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_ros_cpp::clean_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_ros_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'project_ros_cpp': ['/home/jetbot/project_black/src/project_ros_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_cpp::clean_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_cpp::clean_point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_cpp::clean_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_cpp::clean_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_cpp::clean_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_cpp::clean_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_ros_cpp::clean_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc3d368272e33463cb6bcfa0567b445f";
  }

  static const char* value(const ::project_ros_cpp::clean_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc3d368272e33463ULL;
  static const uint64_t static_value2 = 0xcb6bcfa0567b445fULL;
};

template<class ContainerAllocator>
struct DataType< ::project_ros_cpp::clean_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_ros_cpp/clean_point";
  }

  static const char* value(const ::project_ros_cpp::clean_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_ros_cpp::clean_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] clean_data\n"
"int32 max_gird_point\n"
;
  }

  static const char* value(const ::project_ros_cpp::clean_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_ros_cpp::clean_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clean_data);
      stream.next(m.max_gird_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clean_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_ros_cpp::clean_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_ros_cpp::clean_point_<ContainerAllocator>& v)
  {
    s << indent << "clean_data[]" << std::endl;
    for (size_t i = 0; i < v.clean_data.size(); ++i)
    {
      s << indent << "  clean_data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.clean_data[i]);
    }
    s << indent << "max_gird_point: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_gird_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_ROS_CPP_MESSAGE_CLEAN_POINT_H
