// Generated by gencpp from file project_ros_cpp/step_one_flag.msg
// DO NOT EDIT!


#ifndef PROJECT_ROS_CPP_MESSAGE_STEP_ONE_FLAG_H
#define PROJECT_ROS_CPP_MESSAGE_STEP_ONE_FLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_ros_cpp
{
template <class ContainerAllocator>
struct step_one_flag_
{
  typedef step_one_flag_<ContainerAllocator> Type;

  step_one_flag_()
    : done_flag(0)  {
    }
  step_one_flag_(const ContainerAllocator& _alloc)
    : done_flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _done_flag_type;
  _done_flag_type done_flag;





  typedef boost::shared_ptr< ::project_ros_cpp::step_one_flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_ros_cpp::step_one_flag_<ContainerAllocator> const> ConstPtr;

}; // struct step_one_flag_

typedef ::project_ros_cpp::step_one_flag_<std::allocator<void> > step_one_flag;

typedef boost::shared_ptr< ::project_ros_cpp::step_one_flag > step_one_flagPtr;
typedef boost::shared_ptr< ::project_ros_cpp::step_one_flag const> step_one_flagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_ros_cpp::step_one_flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_ros_cpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'project_ros_cpp': ['/home/jetbot/project_black/src/project_ros_cpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_ros_cpp::step_one_flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_ros_cpp::step_one_flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_ros_cpp::step_one_flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17baec0563bbecdba8661f601b44ff3e";
  }

  static const char* value(const ::project_ros_cpp::step_one_flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17baec0563bbecdbULL;
  static const uint64_t static_value2 = 0xa8661f601b44ff3eULL;
};

template<class ContainerAllocator>
struct DataType< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_ros_cpp/step_one_flag";
  }

  static const char* value(const ::project_ros_cpp::step_one_flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 done_flag\n"
;
  }

  static const char* value(const ::project_ros_cpp::step_one_flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct step_one_flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_ros_cpp::step_one_flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_ros_cpp::step_one_flag_<ContainerAllocator>& v)
  {
    s << indent << "done_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.done_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_ROS_CPP_MESSAGE_STEP_ONE_FLAG_H
